module.exports = {
  apps: [
    {
      name: 'jobs-website',
      cwd: '/var/www/jobs',
      script: 'src/server.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3004,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3004,
      },
      error_file: '/var/www/jobs/logs/error.log',
      out_file: '/var/www/jobs/logs/output.log',
      log_file: '/var/www/jobs/logs/combined.log',
      time: true,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'jobs-alerts',
      cwd: '/var/www/jobs',
      script: 'src/jobs/emailAlerts.js',
      args: '--force --frequency=all',
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: '0 8 * * *', // Daily at 8 AM
      env_production: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'jobs-telegram-bot',
      cwd: '/var/www/jobs',
      script: 'src/jobs/telegramBot.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env_production: {
        NODE_ENV: 'production',
      },
      error_file: '/var/www/jobs/logs/telegram-error.log',
      out_file: '/var/www/jobs/logs/telegram-output.log',
      time: true,
    },
    {
      name: 'jobs-scraper',
      cwd: '/var/www/jobs',
      script: 'src/scrapers/scheduler.js',
      args: '--cron',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env: {
        NODE_ENV: 'development',
      },
      env_production: {
        NODE_ENV: 'production',
      },
      error_file: '/var/www/jobs/logs/scraper-error.log',
      out_file: '/var/www/jobs/logs/scraper-output.log',
      time: true,
      merge_logs: true,
    },
  ],
};
